- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: print the USERNAME
    private: true

  - name: PASSWORD
    prompt: print the PASSWORD
    private: true
  tasks:
  - name: printing user information
    ansible.builtin.debug:
      msg: "Hello username is : {{ USERNAME }}, password is : {{ PASSWORD }}"

