- name: variables by Preferences
  hosts: local
  connection: local
  vars:
    COURSE: Devops Engineer from Play
  vars_files:
  - 06-course.yaml
  vars_prompt:
  - name: Devops
    prompt: Print the Course name
    private: true
  tasks:
  - name: Print the variables
    vars:
      COURSE: "Hey from task"
    ansible.builtin.debug:
      msg: "{{ COURSE }}"




  